### ISSUE TITLE
Chat or "support" for Blitz++

### ISSUE THREAD

**Issue by ClmnsRck** [blitzpp/blitz#103]
Is there a chat, online forum or anything like it for Blitz++?
I have some questions(and will continue to have some) i would ike to as experienced users, but do not fit the issues tab of github.

Right now, i would like if there is a way to access the data array behind the tensor?

**Comment by slayoo** [comment]
Hello, github issues seem apt to me. The other option is to post to the blitz-support mailing list which is still hosted on SourceForge: https://sf.net/p/blitz/mailman/

Re "is a way to access the data array behind the tensor?": if you mean to access the raw memory region, the Array class has several methods: data(), dataZero() and dataFirst() - see page 22 of the v0.9 manual (http://physik.uni-graz.at/~crg/Programmierkurs1112/pdfs/blitz.pdf).

**Comment by citibeth** [comment]
Use a loop plus the standard c++ random number generator

http://www.cplusplus.com/reference/random/mt19937/

**Comment by ClmnsRck** [comment]
One last question then I will close this issue, to not spam into the issues tab:
```
C = sum(A(a,b,c) * B(c,d,e),c);
```
Is this the fastest way right now, to do a Tensor-Dot-Product(Tensor-Inner-product) in Blitz++?
