### ISSUE TITLE
How to ensure maximum ressource usage?

### ISSUE THREAD

**Issue by ClmnsRck** [blitzpp/blitz#104]
I would like to know, what compilerflags i have to set if i want to ensure, that blitz runs at its fullest potential. Right now, i have installed it, but not really taken further precautions.

EDIT: `-O3` and `-march=native` are being used

**Comment by slayoo** [comment]
You can also try ``-Ofast`` instead of -O3 if you don't rely on NaN arithmetics and alike.

**Comment by citibeth** [comment]
Optimizing numerical libraries for a particular purpose is a black art and
depends on many factors; the most important being how you lay out memory
for your particular problem.  See here also:

https://stackify.com/premature-optimization-evil/

All of this is a way of saying... I have no idea which compiler flags will
make Blitz++ work fastest for your problem.  If you need to know, then you
will have to run the experiments.  We would be interested in hearing any
results, of course.

-- Elizabeth
