### ISSUE TITLE
The Bundled documentation link in wiki is broken

### ISSUE THREAD

**Issue by Little-Flower-171** [blitzpp/blitz#106]
[This page](https://github.com/blitzpp/blitz/wiki/Documentation,-etc) shows the bundled documentation link "http://physik.uni-graz.at/~crg/Programmierkurs1112/pdfs/blitz.pdf". When I click this link at 11:21 AM, March 29, 2019, Coordinated Universal Time (UTC), it shows:

[![Broken link](https://user-images.githubusercontent.com/36354459/55229433-f48ca080-5257-11e9-962a-67d272a1cc7c.png)](http://physik.uni-graz.at/~crg/Programmierkurs1112/pdfs/blitz.pdf)

**Comment by slayoo** [comment]
[blitz-0.9.pdf](https://github.com/blitzpp/blitz/files/3031673/blitz-0.9.pdf)

**Comment by slayoo** [comment]
Thanks!
The file is uploaded above, and the wiki is now pointing to this one.
I plan to include generation of the pdf in the Travis CI script to streamline updating it... stay tuned
