### ISSUE TITLE
Most efficient way to do tensor-dot-product

### ISSUE THREAD

**Issue by ClmnsRck** [blitzpp/blitz#107]
```
C = sum(A(a,b,c) * B(c,d,e),c);
```
Is this the fastest way right now, to do a Tensor-Dot-Product(Tensor-Inner-product) in Blitz++?

**Comment by citibeth** [comment]
I don’t know.  Blitz us more arrays not tensors.  Have you considered
Eigen’s tensor capabilities?

**Comment by ClmnsRck** [comment]
I am currently comparing several libraries with tensor-capabilities, such as Fastor, eigen, FTensor, blitz++ and xtensor, which is why i would like to be so fair as to use the most efficient way to do certain tasks.

**Comment by citibeth** [comment]
Thanks I’m curious about the results!

I use blitz over Eigen for multi dim arrays for reasons other than tensor
algorithms.  (I’m also heavily reliant on Eigen for sparse on sparse matrix
multiplication).  The people at Eigen are really smart and, my guess is,
hard to beat in speed.

**Comment by ClmnsRck** [comment]
eigens 3D-Tensor multiplication is extremely well optimised, even to the point, that 1GB tensors times other 1GB tensors only take something aroung 5-10 seconds to complete. I'll make sure to come back to show the results once my tests are reliable enough.

**Comment by citibeth** [comment]
I would also try examples where youbiterate thrrough the loop explicitly

**Comment by ClmnsRck** [comment]
So like a base case? sequentially going through every index, to see a baseline performance?

**Comment by citibeth** [comment]
I mean, just write it yourself as a nested loop like one would do in fortran
