### ISSUE TITLE
request/question Multithreading support for blitz++

### ISSUE THREAD

**Issue by ClmnsRck** [blitzpp/blitz#110]
Is Multithreading support built into Blitz++? Like TBB oder OpenMP? i have tried compiling blitz++ code with `-ltbb -fopenmp`(becuase of other code in there to), but it did nothing to the performance.

**Comment by papadop** [comment]
I think there is some multi-threading support in blitz, but this predates largely TBB or OpenMP times (I remember that the framework is named tau something). I have not seen any #pragma in current (well a few months back) blitz code, so do not expect openmp to work.

**Comment by slayoo** [comment]
The reference-countic logic in Blitz can be made thread-safe with a relevant preprocessor define (see docs). This triggers locking of increment/decrement operations on ref counts and of course affects performance (hence disabled by default). No multi-threaded operations are included. HTH



On Tue, Apr 9, 2019 at 3:23 PM +0200, "ClmnsRck" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is Multithreading support built into Blitz++? Like TBB oder OpenMP? i have tried compiling blitz++ code with -ltbb -fopenmp(becuase of other code in there to), but it did nothing to the performance.

**Comment by WalterZimmer314** [comment]
Depends on your understanding of "Multithreading support".

The data structures itself are thread safe, so they can be used in multithreaded applications, e.g. openMP.

The implemented algorithms however are not parallelized, e.g. If you calculate the sin() of each element in an array, this is executed as one loop on a single core. You can however distribute multiple calculation over different arrays on different cores via a parallelization framework like OpenMP.

If you need the former, use some dedicated library for that (BLAS, LAPACK, ...), which you need probably anyway as Bliz++ implements the basic algorithms only.
