### ISSUE TITLE
[operator+, set, fill] Help with finding funcionality

### ISSUE THREAD

**Issue by ClmnsRck** [blitzpp/blitz#113]
Hey, i cant find some operations in the Documentation:
1. adding a scalar to any type of Array
2. how to fill a array with one single value for all cells

Could somebody help me here?

**Comment by lutorm** [comment]
It's been a while since I used blitz, but does the obvious syntax not work?

A = 1.0;
A += 1.0;

**Comment by ClmnsRck** [comment]
Actually it does, i got a weird error, that kind of demotivated me, but after just writing, what i thougt was right, it worked.
