### ISSUE TITLE
[bug] index-operators fail if not int

### ISSUE THREAD

**Issue by ClmnsRck** [blitzpp/blitz#115]
When doing something like this:
```
for(long i = 0; i < SIZE; ++i){
    array(i,0) = 1;
}
```
It fails, as `long` does not seem supported ... neither is `size_t` nor `uint64_t`.

**Comment by ClmnsRck** [comment]
either i am really lucky while doing something forbidden, or there is something wrong, as not even `uint32_t` is supported

**Comment by AnderOne** [comment]
See [#111 (comment)](https://github.com/blitzpp/blitz/issues/111#issuecomment-481584393)
