### ISSUE TITLE
review & migrate bugreports from SF

### ISSUE THREAD

**Issue by slayoo** [blitzpp/blitz#13]
as of today:
- 36 bugs: https://sourceforge.net/p/blitz/bugs/
- 12 patches: https://sourceforge.net/p/blitz/patches/
- 5 feature requests: https://sourceforge.net/p/blitz/feature-requests/

**Comment by citibeth** [comment]
Sylwester,

Would you like to do this migration?

-- Elizabeth

**Comment by slayoo** [comment]
Elizabeth, 

I aim at least to migrate those that I've submitted at SF. Time permitting, I'll try to check the others as well.

**Comment by slayoo** [comment]
All feature requests migrated.

**Comment by slayoo** [comment]
2 bugs and 10 patches left - that's it for today.

**Comment by slayoo** [comment]
Finished.
