### ISSUE TITLE
spack installation not working on ubuntu 18.04

### ISSUE THREAD

**Issue by trontrytel** [blitzpp/blitz#143]
FYI: I tried installing blitz on ubuntu 18.04 with spack but it didnt work. I'm not sure but this might be a reason:

https://github.com/spack/spack/pull/4048

The standard cmake routine worked like a charm. Your docs seem to strongly recommend spack, so this might be worth mentioning?

**Comment by slayoo** [comment]
Aniu! Never used spcak myself, but doesn't "sudo apt-get install libblitz0-dev" work on Ubuntu? S.

**Comment by trontrytel** [comment]
Sylwestrze Fancy meeting you here! 

Unfortunately it does not work for Ubuntu 18.04 (Works for 16.04 and 18.10, but I can't use those for other reasons.)

**Comment by slayoo** [comment]
For the record, I've just asked on Ubuntu website about the lack of availability for 18.04:
https://answers.launchpad.net/ubuntu/+source/blitz++/+question/681496

**Comment by citibeth** [comment]
Can you please post the log files when you try to install?  That would be
super helpful in diagnosing this issue.

Thank you,
-- Elizabeth

**Comment by slayoo** [comment]
For the record, here's the answer concerning Ubuntu bionic:
> Apparently at the time of publishing Ubuntu bionic, there was a problem with the blitz++ software that did not allow compiling the package. It seems that meanwhile this problem has been solved, and blitz++ packages are available for newer Ubuntu releases.

**Comment by trontrytel** [comment]
> Can you please post the log files when you try to install? That would be super helpful in diagnosing this issue. Thank you, -- Elizabeth

I think the issue will be solved with the spack pull I mentioned before. Cmake installation worked perfectly for me, so I got my blitz++.

**Comment by slayoo** [comment]
I guess little more can be done here.
BTW, autotools build has just been phased out in favour of CMake
