### ISSUE TITLE
cmake version required

### ISSUE THREAD

**Issue by ossak032** [blitzpp/blitz#152]
Dear,
I found that CMake 3.12 or higher is required to install blitz.
However the version on my Ubuntu 18 is 3.10.2
Do you have any idea to install blitz with an old version cmake or without cmake?
Thank you.
Youngseob

**Comment by papadop** [comment]
There is a cmake_minimum_version that is set to 3.12 somewhere. Try to reduce it to 3.10 and see what breaks.... I do not remember exactly why we required 3.12, but it is probably  vert localized as I used to build with  cmake for alors 10 years, so well before even 3.10.     Le 29 nov. 2019 11:38 AM, Youngseob Kim <notifications@github.com> a écrit :Dear,
I found that CMake 3.12 or higher is required to install blitz.
However the version on my Ubuntu 18 is 3.10.2
Do you have any idea to install blitz with an old version cmake or without cmake?
Thank you.
Youngseob
