### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by David-A-Blankenship** [blitzpp/blitz#153]
I use blitz on Windows and have updated the CMake files, and one header file, to handle the build on Windows including boost serialization. I would like permission to push my branch and create a pull request to get these changes in the repository.  I am actively working with blitz and may be able to contribute additional changes in the future, such as cleaning up some of the compiler warnings generated on Windows and maybe help with CMake.

Changes:
blitz/blitz.h - to add __declspec for #ifdef WIN32
cmake/BlitzConfigFileName.cmake - to change EQUAL to STREQUAL 
cmake/Win32Compat.cmake - to change the CMAKE_RUNTIME_OUTPUT_DIRECTORY to CMAKE_BINARY_DIR/src
src/CMakeLists.txt - to add find_package for Boost serialization if ENABLE_SERIALISATION

Tested:
Windows
* CMake 3.15.2
* MSVS 2019 version 16.3.9
* Boost 1.70.0

CentOS
* CMake 3.15.3
* gcc 8.3.1 20190311 (Red Hat 8.3.1-3)
* Boost 1.70.0

I did not see any other way to contact someone about permissions to push.

Thanks.

David

**Comment by David-A-Blankenship** [comment]
Here are the cmake command lines that I used to create the projects.

Windows:
cmake.exe" -DENABLE_SERIALISATION=1 -G"Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX="c:/dev/blitz" ..

CentOS:
cmake -DENABLE_SERIALISATION=1 -DCMAKE_INSTALL_PREFIX="/home/dblanken/blitz" -DCMAKE_BUILD_TYPE=Debug ..

**Comment by papadop** [comment]
I do not think I can grant you the rights you ask. But I can make a suggestion. Why don't you clone the git repo, create the branch on your clone and ask for a PR from there (you can ask a PR to the original repo) ??? That should always work...

**Comment by David-A-Blankenship** [comment]
Thank you. I will give that a try.

**Comment by slayoo** [comment]
closing as we have the PR now #154 
Thank you!
