### ISSUE TITLE
unravel calculation

### ISSUE THREAD

**Issue by dkokron** [blitzpp/blitz#167]
I'm hoping some blitz++ expert can help me unravel the following calculation.

int ub1=46+1, ub2=18+1, ub3=5+1, ub4=6+1;
Array<double, 4> rjac(ub1,ub2,ub3,ub4);
Array<double, 2> fjac(ub2,ub4);
Array<double, 3> pv(ub1,ub2,ub3);
rjac += fjac(i2,i4) * pv(i1,i2,i3);

My attempt to convert this into a simple loop nest gives the wrong results.  Can anyone tell me what I'm doing wrong?

  const double * restrict   pvp =   pv.data();
  const double * restrict fjacp = fjac.data();
        double * restrict rjacp = rjac.data();
  for (int o=0; o<oub; ++o) { // 0:46
    for (int n=0; n<nub; ++n) { // 0:18
      for (int m=0; m<mub; ++m) { // 0:5
        for (int l=0; l<lub; ++l) { // 0:6
          rjacp[o*(lub*mub*nub) + n*(lub*mub) + m*lub + l] += fjacp[n*lub + l] * pvp[o*(nub*mub) + n*mub + m];
        }
      }
    }
  }

**Comment by slayoo** [comment]
Please provide an example that compiles. In the code you provided, i1, i2, i3, i4 are undefined.
You can use backticks (https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks) to paste C++ code conveniently, so Github will preserve indentation and do syntax highlighting. E.g.,.

```c++
#include <blitz/array.h>

int main()
{
    using namespace blitz;
    ...
}
```
