### ISSUE TITLE
Header files

### ISSUE THREAD

**Issue by gleb-kun** [blitzpp/blitz#183]
In the "examples" folder I saw the inclusion of header files, for example these ([examples/pick.cpp](https://github.com/blitzpp/blitz/blob/39f885951a9b8b11f931f917935a16066a945056/examples/pick.cpp#L5)):
```
#include <blitz/vector-et.h>
#include <blitz/vecpick.h>
```
However I can't find them in the project, are they outdated files?

**Comment by citibeth** [comment]
Apparently so, there is no guarantee any examples will work.

**Comment by gleb-kun** [comment]
Thanks for the answer.
