### ISSUE TITLE
discuss code archived in pre-github branches

### ISSUE THREAD

**Issue by slayoo** [blitzpp/blitz#26]
There are three development (i.e. work-in-progress?) branches preserved from pre-github times (see https://github.com/blitzpp/blitz/branches):
- stencil-et
- compat-64bit
- vectorization

Would be great to leverage the code developed there!

**Comment by citibeth** [comment]
Would you like to submit a pull request to the Git repo?

BTW... I consider Blitz++ to be in strictly maintenance mode.  On my
off-hours, I'm working on a replacement that will work more seamlessly with
C++11.

-- Elizabeth

**Comment by lutorm** [comment]
As noted on those branches, the relevant code has already been merged.

Cheers,

/Patrik

**Comment by slayoo** [comment]
Great! Thank you Patrik!
Elisabeth, I'm looking forward to hearing more news!
P.S. I'm working right now on Travis and Appveyor continuous integration scripts for this repo, pull request soon.
Sylwester

**Comment by slayoo** [comment]
Well, in fact reopening as perhaps these branches could be deleted then?

**Comment by lutorm** [comment]
I think the correct action in hg is to "close" the branches, which I did. I
don't think you can delete them in hg.

If they're still showing up in git, then yeah, they can be deleted.



On Wed, Mar 28, 2018 at 10:07 AM, Sylwester Arabas <notifications@github.com

**Comment by slayoo** [comment]
On github they still show up as candidates for pull requests, in the branches tab there are the red trash bin icons to delete/deactivate them:
![image](https://user-images.githubusercontent.com/89685/38053667-6bab9824-32dd-11e8-963e-a8eedd3f669d.png)

**Comment by slayoo** [comment]
Here is the Travis-CS pull request:https://github.com/blitzpp/blitz/pull/27

**Comment by slayoo** [comment]
![image](https://user-images.githubusercontent.com/89685/39697603-1cc36638-51fa-11e8-9e8a-45722e68f64a.png)
