### ISSUE TITLE
Create CMake Build

### ISSUE THREAD

**Issue by citibeth** [blitzpp/blitz#4]
Convert from autotools --> CMake

**Comment by lutorm** [comment]
Is there a specific deficiency in the autotools setup that needs fixing?

**Comment by citibeth** [comment]
No, nothing specific.  But having tried both, I MUCH prefer CMake.  And I'm
not the only one.  When I did a Google search for "migrate CMake to
Autotools," what I found instead was legions of projects moving the other
way.  Autotools seems to be dying a well-deserved death because it's so
arcane.  CMake's main claim to fame is it's not as bad as Autotools.

**Comment by floswald** [comment]
+1 for CMake

**Comment by slayoo** [comment]
Just for the record, if you only want to find Blitz++ library from CMake, this works:

    find_package(PkgConfig)
    pkg_check_modules(BLITZ QUIET blitz>=0.10)
    if (NOT BLITZ_FOUND)
        ...

**Comment by floswald** [comment]
That's actually true. I use it that way as well. So for users there is not
much to gain. I just thought to develop the library a cmake build would be
useful.

**Comment by youngmit** [comment]
CMake is more cross-platform as well. Users on Windows would have a much better experience building Blitz if there is a proper CMake config, and the developers wouldn't have to maintain VS solutions in parallel with the autotools build system. Going the way of CMake will also open the door to including Blitz++ in the various C++ package manager ecosystems that are cropping up.

**Comment by youngmit** [comment]
I would be happy to take a stab at this if there is any indication that it would be accepted upstream.

**Comment by citibeth** [comment]
Yes it would be

**Comment by papadop** [comment]
I already have one such build. Though I must say that I have not updated it recently. If you are interested it can at least be a starting point.... I need to check where the last version is and separate it from other changes but if you are interested I will make it available.TheoLe 19 févr. 2019 8:27 PM, Elizabeth Fischer <notifications@github.com> a écrit :Yes it would be



On Tue, Feb 19, 2019 at 14:20 Mitchell T.H. Young <notifications@github.com>

wrote:

**Comment by citibeth** [comment]
That would be great, can you submit a PR?

**Comment by papadop** [comment]
This is PR #97...

**Comment by youngmit** [comment]
Just took the time to get myself familiar with the discussion surrounding the PR. I think this is a better starting point than I am willing to recreate on my own. I agree with the sentiment that maintaining the two build systems in parallel without modifying some of the code will result in a considerable maintenance burden and increased complexity. I first thing that I ran into making my own CMake config that was particularly annoying was the interrogation of various compiler features, which are now several standard old (HAVE_BOOL... really?). I think in the context of a lot of the tasks that @citibeth wants to tackle to modernize the code base should probably be done in concert with a new CMake build config. Just getting rid of the vast majority of the stuff in the config headers that aren't standard in C++11 is a good start and should yield a much simpler CMake. Not sure how we could effect that with manageable PRs though.

**Comment by citibeth** [comment]
If we have a working CMake build I don’t want to maintain the old build
going forward

**Comment by slayoo** [comment]
this is addresed in #97, #123 and #124
