### ISSUE TITLE
Travic Continuous Integration

### ISSUE THREAD

**Issue by citibeth** [blitzpp/blitz#6]
Jeff Hammond wrote:

Whenever this ends up on Github, I'll be happy to contribute Travis CI (continuous integration i.e. automated testing) support, since I'm on a role with that lately. CI will be particularly useful when pull requests start coming in and C++11 features are added.

**Comment by slayoo** [comment]
See:https://github.com/blitzpp/blitz/pull/27

**Comment by slayoo** [comment]
Closing as we have Travis and Appveyor running, will open a new one with a wishlist of enhancements to the CI process
