### ISSUE TITLE
patch to fix out-of-source build problem 

### ISSUE THREAD

**Issue by slayoo** [blitzpp/blitz#82]
Patch proposed by Seth Johnson (@sethrj?) migrated from SF: https://sourceforge.net/p/blitz/patches/12/

> Out-of-source builds failed (when doing "make lib install") because the dependencies on the executables created in "blitz/generate" use a relative path. The attached patch substitutes the top source dir with the top build dir.

```diff
Index: blitz/generate/Makefile.am
===================================================================
RCS file: /cvsroot/blitz/blitz/blitz/generate/Makefile.am,v
retrieving revision 1.17
diff -r1.17 Makefile.am
47c47
< 	./$(patsubst %.cpp,%$(EXEEXT),$<)
---
> 	$(patsubst %.cpp,%$(EXEEXT),$(subst $(top_srcdir),$(top_builddir),$<))
50c50
< 	./$(patsubst %.cpp,%$(EXEEXT),$<)
---
> 	$(patsubst %.cpp,%$(EXEEXT),$(subst $(top_srcdir),$(top_builddir),$<))
```

**Comment by sethrj** [comment]
Hah! Yes, that was indeed me, ages ago :)

**Comment by citibeth** [comment]
@slayoo this looks reasonable enough, can it be merged safely?

**Comment by slayoo** [comment]
PR created: https://github.com/blitzpp/blitz/pull/100
