### ISSUE TITLE
patch: Functions: FFT, IFFT, IWT, IWT2

### ISSUE THREAD

**Issue by slayoo** [blitzpp/blitz#87]
Migrated from SF: https://sourceforge.net/p/blitz/patches/2/
Reported back in 2002 by  Suresh kumar (@mdsuresh here?):

[functions.zip](https://github.com/blitzpp/blitz/files/2407655/functions.zip)

Original comment: 
> 1-d vectorized FFT/IFFT (tested)
> Shuffle, BitReverse, FFT, IFFT
> 
> 1-d vectorized FWT/IFWT (wavelet) (tested)
> Uphi, DownHi, UpLo, DownLo, FWT_PO, IWT_PO
>
> 2-d FWT/IFWT (wavelet) (tested, but not completely)
> FWT2_PO, IWT2_PO
>
> 1-d vectorized FWT( walsh transform) (tested)
> FWT, IFWT
>
> vectorized matrix inverse (tested)
> Inv
> matrix svd (tested)
> SVD , conditional SVD
> matrix pesudo inverse (tested)
> PInv
>
> matrix LU decomposition (tested)
> LU, LUBSB, LUInverse
>
> matrix Cholesky decompostion (untested)
> LL, LLBSB
>
> HighPrecision Arthimetic( uncompiled)
>
> and have applied a TEMPORARY patch to Range just to
> get the range to be divisible by the stride.
> [Not Included]
>
> And added a dummy Array::ascending(int) const to
> get tensor multiplication to compile for version 0.6.
> [Not Included]
>
> thanks, hopefully u will like it.
> -suresh

**Comment by citibeth** [comment]
How does this compare to FFTW?  I'd rather not maintain FFTs that, ultimately, are inferior to something else already out there.
