### ISSUE TITLE
Can't build: error: can't execute /bin/bash config/config.sub

### ISSUE THREAD

**Issue by Tafnab** [blitzpp/blitz#93]
Is there a build guide for this package on Linux somewhere? I don't see Blitz++ offered as a package on my distro (Linux Mint 19.1).  I discovered through trial and error to run
aclocal
autoconf
./configure
in the master directory downloaded as a zip from Github. There also appear to be quite a few options, none of which I understand, in the configuration file. Are any of these supposed to be edited manually? How can I create the config.sub (not sure what this is doing, this is very unusual compared to other builds). 
Best,

**Comment by slayoo** [comment]
Thanks for the message. There is no build guide I know of that would match the current version.
We can try to help here as much as we can, some hints are also perhaps to be found in the .travis.yml file which is used to automate the build on Linux for continuous integration: https://github.com/blitzpp/blitz/blob/master/.travis.yml

**Comment by citibeth** [comment]
Steps to build Blitz++

1. Download Spack auto-installer and get acquainted with it:
     https://spack.io/

2. Type `spack install blitz`

3. If anything goes wrong, post to the Spack email list or Issues section
on GitHub.

4. If you really REALLY prefer doing things the hard way and like
installing things manually, then look inside the Spack recipe for Blitz,
and it will show you any weird thing it does, beyond "./configure;make;make
install".   But seriously... learning Spack will be easier, and will give
you a TON of dividends in the long run.

Good luck!
-- Elizabeth

**Comment by Tafnab** [comment]
Slayoo: The .travis.yml is as good as a build guide. I would put something on the front page saying to consult it for build instructions. Everything built fine & passed tests on Linux Mint 19.1 using g++ & gfortran 8.2.0 and gcc 7.3.0. (I forgot to set the C compiler to the new version). Thanks.
