### ISSUE TITLE
PGI compiler is detected as GNU on linux

### ISSUE THREAD

**Issue by mic84** [blitzpp/blitz#94]
Building with CXX=pgc++ does not have the expected outcome. The compiler is detected as GNU, CXXFLAGS is set to the default GNU flags and the compiler specific header is GNU-specific (gnu/bzconfig.h). As a result, make check fails to compile. I played around with  **m4/ac_cxx_flags_preset.m4** and **m4/ac_fortran_flags_preset.m4** and managed to load the correct flags preset. However, the compiler specific header is still GNU-specific and 'configure' still reports the compiler as being GNU.

**Comment by citibeth** [comment]
Please try building Blitz++ with the PGI compilers using Spack: https://spack.io.  Spack knows a lot of tricks about compilers that we do not.  If Spack cannot build with PGI, please open an Issue on the Spack GitHub repo, and someone who knows about PGI compilers will help you there (and help improve Spack as well, for the next person in your situation):
https://github.com/spack/spack

In the event that the ultimate resolution requires a change to Blitz++, please feel free to re-open this thread (or even better, submit a PR).  See also text at:

https://github.com/blitzpp/blitz/blob/master/README.md
